name: proj_2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.3
  - pip=25.2
  - python=3.9.23
  - readline=8.2
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - chumpy==0.70
      - click==8.1.8
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.3
      - contourpy==1.3.0
      - coverage==7.10.7
      - crcmod==1.7
      - cryptography==46.0.1
      - cycler==0.12.1
      - cython==3.1.4
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dnspython==2.7.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.118.0
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - flake8==7.3.0
      - flatbuffers==25.9.23
      - fonttools==4.60.0
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - interrogate==1.7.0
      - ipykernel==6.30.1
      - ipython==8.18.1
      - isoduration==20.11.0
      - isort==4.3.21
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.5.2
      - json-tricks==3.17.3
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - lark==1.3.0
      - lmdb==1.7.3
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mat4py==0.6.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - mmcv==2.1.0
      - mmdet==3.2.0
      - mmengine==0.10.7
      - mmpretrain==1.2.0
      - model-index==0.1.11
      - modelindex==0.0.2
      - mpmath==1.3.0
      - munkres==1.1.4
      - narwhals==2.6.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.13.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - onnx==1.19.0
      - onnxoptimizer==0.3.13
      - onnxruntime==1.19.2
      - opencv-python==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - ordered-set==4.1.0
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.4.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py==1.11.0
      - pyarrow==21.0.0
      - pycocotools==2.0.10
      - pycodestyle==2.14.0
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pymongo==4.15.2
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytest-runner==6.0.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pyturbojpeg==1.8.2
      - pytz==2023.4
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==13.4.2
      - rpds-py==0.27.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.48.0
      - streamlit==1.50.0
      - streamlit-autorefresh==1.0.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - termcolor==3.1.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.2.1
      - tornado==6.5.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - uvicorn==0.37.0
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - xdoctest==1.3.0
      - xgboost==2.1.4
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - zipp==3.23.0
